### PR TITLE
Add manifesto

### PR DESCRIPTION
**Pull request by mjackson**
This is a first pass at putting some text up that helps people understand our vision for rackt; what it is and how they can contribute. Feedback would be appreciated :)

Thanks!

ping @rackt/owners

### CODE REVIEW

**Comment by knowbody** [comment]
I really like it Michael!

**Comment by gaearon** [comment]
Love this!

**Comment by ryanflorence** [comment]
I kinda rewrote it again:  how about this https://gist.github.com/124070e7c4b3839d4573 ?

**Comment by knowbody** [comment]
Like this even more @ryanflorence

**Pull request merged**
