### PR TITLE
Upgrade Code of Conduct

### PR DESCRIPTION
**Pull request by timdorr**
Coraline pushed out a newer version a week or two ago that's great. I think we should keep in lock step with it, since it's added some important points. Namely, the positive behavior section.

### CODE REVIEW

**Comment by taion** [comment]
Do we need a broad CoC? I would strongly, strongly prefer to stay as far away as humanly possible from _any_ of the CoC-related controversies.

**Comment by taion** [comment]
Ref https://bugs.ruby-lang.org/issues/12004.

If we _need_ a CoC, can we use a looser one?

The meta-discussion around the contributor covenant is the most actively toxic thing I've seen on the internet lately. There is no discussion I want less to be party to.

**Comment by taion** [comment]
cc @mjackson

**Comment by timdorr** [comment]
The whole Ruby issue was a giant shit show. Not looking to bring that here.

Using a CoC signals to me that project maintainers have at least *thought* about the issue. @mjackson added it, so I gather he's thinking about it in some capacity. I'm just updating it to the latest version. I don't really have strong feelings about it one way or another.

**Comment by taion** [comment]
That's exactly the problem though.

The contributor covenant is effectively a political document at this point, and it's leading to the worst kind of politics. I want absolutely no part of it.

**Comment by timdorr** [comment]
Well, like I said, I don't have strong opinions on it. My general sense is it does a net positive for those that don't feel like they can contribute or feel excluded by some potential for behavior in the project. I don't experience that myself, hence my opinion isn't strong.

**Comment by taion** [comment]
I just really, really do not want to be party to anything that's this controversial in this context.

**Comment by mjackson** [comment]
I sympathize with @taion in this regard. I guess I just thought that since it was something that lots of other projects have already adopted that we could just use it and never talk about it again. But the contributor covenant has definitely taken on more of a political meaning since the whole Ruby debacle.

A possible, simpler alternative could be the [Postgres CoC](http://www.postgresql.org/message-id/5699131D.2040805@commandprompt.com):

```
== PostgreSQL Community Code of Conduct (CoC) ==

This document provides community guidelines for a safe, respectful, 
productive, and collaborative place for any person who is willing to 
contribute to the PostgreSQL community. It applies to all "collaborative 
space", which is defined as community communications channels (such as 
mailing lists, IRC, submitted patches, commit comments, etc.).

* We are tolerant of people’s right to have opposing views.

* Participants must ensure that their language and actions are free
of personal attacks and disparaging personal remarks.

* When interpreting the words and actions of others, participants
should always assume good intentions.

* Participants who disrupt the collaborative space, or participate in a 
pattern of behaviour which could considered harassment will not be 
tolerated.
```

**Comment by timdorr** [comment]
I'd be cool with that. Not looking to charge things politically. Just updating a dep :smile:

**Comment by taion** [comment]
That Ruby thread is scarily long. Following it a bit more, this was the most recent draft of the PostgreSQL CoC, I believe: http://www.postgresql.org/message-id/56A2E9C5.2040707@commandprompt.com

```
== PostgreSQL Community Code of Conduct (CoC) ==

This document provides community guidelines for a safe, respectful, 
productive, and collaborative place for any person who is willing to 
contribute to the PostgreSQL community. It applies to all "collaborative 
space", which is defined as community communications channels (such as 
mailing lists, IRC, submitted patches, commit comments, etc.).

* Participants will be tolerant of opposing views.

* Participants must ensure that their language and actions are free
of personal attacks and disparaging personal remarks.

* When interpreting the words and actions of others, participants
should always assume good intentions.

* Behaviour which can be reasonably considered harassment will not be 
tolerated.
```

It looks like they're going to do a bit more exploratory work before formally adopting anything, per http://www.postgresql.org/message-id/56A8516B.8000105@agliodbs.com.

I think something relatively minimal like this is just a good starting point. Especially as discussions for Ruby and Postgres reach more maturity, we can consider following in their footsteps, but I think we invite too much controversy by adopting the contributor covenant in its current form, at the current time.

**Comment by mjackson** [comment]
@timdorr Thank you for being willing to talk about this :)

@taion I like that one even better than the one I posted.

@rackt/owners Are you guys ok w using the Postgres CoC instead of the contributor covenant? Unless someone feels strongly that we should use the contributor covenant, I'd vote we use it.

**Comment by timdorr** [comment]
:+1:

**Comment by knowbody** [comment]
:+1:

**Comment by gaearon** [comment]
Personally I am against switching to a looser CoC because there was some sort of shitstorm in some other communities. I think CC, and especially the latest version, covers exactly why I want my projects to have CoC. It is specific for a reason: having a vague CoC is not much better than having none at all, in my view.

Choosing CoC for an existing project is guaranteed to cause a shitstorm. Luckily we made the choice early, and I haven’t seen any problems so far. I don’t see why we should be backing out of it now. We set the rules here ;-)

**Comment by taion** [comment]
@gaearon 

I'm not opposed to specific projects using different CoCs as desired.

On a broad level, I think the PostgreSQL CoC actually does cover a meaningful amount of bad behavior, including some on my own part, and that CoC is something that I will actively keep in mind.

I'm interpreting this as effectively choosing a CoC for all existing rackt projects, so this isn't greenfield here.

**Comment by gaearon** [comment]
Then do as you see fit :-).
I will keep using CC in the projects that I maintain personally.

**Comment by timdorr** [comment]
Maybe the more vague CoC fits best for an org-wide document, and individual project leaders can determine if they want to use CC or some other, more specific document. As long as we've got some decent org-wide ground rules, that should be sufficient.

**Comment by mjackson** [comment]
Perhaps it makes sense to have a CoC per project then. If Dan wants to use
CC for projects where he is the lead, he should be free to do so. As more
projects join rackt, it may be the case that they have already adopted a
CoC, in which case we don't want to put up a political barrier to them
joining.

The manifesto should probably be updated to say "any applicable Code of
Conduct" instead of linking to a specific one.

**Comment by timdorr** [comment]
I agree with that. FWIW, I think the only really practical issue I've seen relating to a CoC is rudeness, never discrimination or exclusion. And in those few cases, they weren't reading any contribution doc or code of conduct anyways. Otherwise they wouldn't have done that in the first place :smile:

I'll close this out and do another PR for removing the CoC and any site changes.

**Pull request closed without merging**
